### ISSUE TITLE
Pickblocking a barrel will crash you.

### ISSUE THREAD

**Issue by Darkhax** [Epoxide-Software/GYBH#1]
This crash is generated when a chest is pick blocked. Likely fix would be to change the pick block method in the block to return the correct block. An additional fix would be to add null checks to the renderer to prevent hard crashing in the future. 

```
[15:47:26] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering item
	at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.renderItemAndEffectIntoGUI(RenderItemWrapper.java:305) ~[RenderItemWrapper.class:?]
	at net.minecraft.client.gui.GuiIngame.renderHotbarItem(GuiIngame.java:1144) ~[GuiIngame.class:?]
	at net.minecraft.client.gui.GuiIngame.renderHotbar(GuiIngame.java:528) ~[GuiIngame.class:?]
	at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:329) ~[GuiIngameForge.class:?]
	at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:140) ~[GuiIngameForge.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1125) ~[EntityRenderer.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1139) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:406) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
	at org.epoxide.gybh.client.renderer.BarrelItemOverride.handleItemState(BarrelItemOverride.java:44) ~[BarrelItemOverride.class:?]
	at net.minecraft.client.renderer.RenderItem.getItemModelWithOverrides(RenderItem.java:254) ~[RenderItem.class:?]
	at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.getItemModelWithOverrides(RenderItemWrapper.java:341) ~[RenderItemWrapper.class:?]
	at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.renderItemAndEffectIntoGUI(RenderItemWrapper.java:283) ~[RenderItemWrapper.class:?]
	... 20 more
```

**Comment by Darkhax** [comment]
After looking into this issue further, it seems the crash only happens if you pick block an empty barrel. This also revealed a larger bug, in which pick blocking a barrel WITH an item, would give you an item version of the barrel with that. However only the tier should be saved when you pick block.

**Comment by jsaggers** [comment]
Has this been fixed and a build released because it is still happening and drives me nuts.
Nice mod by the way.
EDIT: Doesn't matter what I break it with I get an instant crash.

**Comment by Darkhax** [comment]
@jsaggers Could you please post the crash log?

**Comment by jsaggers** [comment]
Sorry to reopen this. One crash report. 
[crash-2017-03-10_13.21.29-client.txt](https://github.com/Epoxide-Software/GYBH/files/832817/crash-2017-03-10_13.21.29-client.txt)
